# Generated by Django 4.1.7 on 2023-03-25 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="survey.survey"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="survey.question"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="survey.survey"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completed_surveys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="survey.survey"
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="survey.question"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="survey.option"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="survey.submission"
            ),
        ),
    ]
